// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateVenueSeats implements pgx.CopyFromSource.
type iteratorForCreateVenueSeats struct {
	rows                 []CreateVenueSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateVenueSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateVenueSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].VenueSectionID,
		r.rows[0].RowLabel,
		r.rows[0].SeatLabel,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForCreateVenueSeats) Err() error {
	return nil
}

// COPY is used because venue layouts are created
// in bulk and no database generated values need to be returned.
func (q *Queries) CreateVenueSeats(ctx context.Context, arg []CreateVenueSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"venue_seats"}, []string{"id", "venue_section_id", "row_label", "seat_label", "created_at"}, &iteratorForCreateVenueSeats{rows: arg})
}
