// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_seats.sql

package db

import (
	"context"
	"time"

	"github.com/iamconnor4/surge/internal/domain"
)

type CreateEventSeatsParams struct {
	ID          domain.EventSeatID
	EventID     domain.EventID
	VenueSeatID domain.VenueSeatID
	PricePence  int64
	IsAvailable bool
	CreatedAt   time.Time
}

const getEventSeatById = `-- name: GetEventSeatById :one
SELECT id, event_id, venue_seat_id, price_pence, is_available, created_at, updated_at
FROM event_seats WHERE id = $1
`

func (q *Queries) GetEventSeatById(ctx context.Context, id domain.EventSeatID) (EventSeat, error) {
	row := q.db.QueryRow(ctx, getEventSeatById, id)
	var i EventSeat
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.VenueSeatID,
		&i.PricePence,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
