// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/iamconnor4/surge/internal/domain"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (
    id,
    venue_id,
    title,
    description,
    starts_at,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEventParams struct {
	ID          domain.EventID
	VenueID     domain.VenueID
	Title       string
	Description string
	StartsAt    time.Time
	CreatedAt   time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.VenueID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.CreatedAt,
	)
	return err
}

const getEventById = `-- name: GetEventById :one
SELECT id, venue_id, title, description, starts_at, created_at, updated_at
FROM events WHERE id = $1
`

func (q *Queries) GetEventById(ctx context.Context, id domain.EventID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventById, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
