// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/iamconnor4/surge/internal/domain"
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusRefunded  OrderStatus = "refunded"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Event struct {
	ID          pgtype.UUID
	VenueID     pgtype.UUID
	Title       string
	Description string
	StartsAt    time.Time
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}

type EventSeat struct {
	ID          pgtype.UUID
	EventID     pgtype.UUID
	VenueSeatID pgtype.UUID
	PricePence  int64
	IsAvailable bool
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}

type Order struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Status     OrderStatus
	TotalPence int64
	CreatedAt  time.Time
	UpdatedAt  *time.Time
	PaidAt     *time.Time
}

type Ticket struct {
	ID          pgtype.UUID
	OrderID     pgtype.UUID
	EventSeatID pgtype.UUID
	PricePence  int64
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}

type User struct {
	ID        domain.UserID
	Email     string
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt *time.Time
}

type Venue struct {
	ID        domain.VenueID
	Name      string
	CreatedAt time.Time
	UpdatedAt *time.Time
}

type VenueSeat struct {
	ID         pgtype.UUID
	SectionID  pgtype.UUID
	RowLabel   string
	SeatNumber string
	CreatedAt  time.Time
	UpdatedAt  *time.Time
}

type VenueSection struct {
	ID        pgtype.UUID
	VenueID   pgtype.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt *time.Time
}
