// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/iamconnor4/surge/internal/domain"
)

const getUserById = `-- name: GetUserById :one
SELECT id, email, first_name, last_name, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id domain.UserID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
