// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venue_sections.sql

package db

import (
	"context"
	"time"

	"github.com/iamconnor4/surge/internal/domain"
)

const createVenueSection = `-- name: CreateVenueSection :exec
INSERT INTO venue_sections (
    id,
    venue_id,
    name,
    created_at
)
VALUES ($1, $2, $3, $4)
`

type CreateVenueSectionParams struct {
	ID        domain.VenueSectionID
	VenueID   domain.VenueID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateVenueSection(ctx context.Context, arg CreateVenueSectionParams) error {
	_, err := q.db.Exec(ctx, createVenueSection,
		arg.ID,
		arg.VenueID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const getVenueSectionById = `-- name: GetVenueSectionById :one
SELECT id, venue_id, name, created_at, updated_at
FROM venue_sections WHERE id = $1
`

func (q *Queries) GetVenueSectionById(ctx context.Context, id domain.VenueSectionID) (VenueSection, error) {
	row := q.db.QueryRow(ctx, getVenueSectionById, id)
	var i VenueSection
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenueSectionsByIds = `-- name: GetVenueSectionsByIds :many
SELECT id, venue_id
FROM venue_sections WHERE id = ANY($1)
`

type GetVenueSectionsByIdsRow struct {
	ID      domain.VenueSectionID
	VenueID domain.VenueID
}

func (q *Queries) GetVenueSectionsByIds(ctx context.Context, venueSectionIds []domain.VenueSectionID) ([]GetVenueSectionsByIdsRow, error) {
	rows, err := q.db.Query(ctx, getVenueSectionsByIds, venueSectionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVenueSectionsByIdsRow
	for rows.Next() {
		var i GetVenueSectionsByIdsRow
		if err := rows.Scan(&i.ID, &i.VenueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
