// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package db

import (
	"context"

	"github.com/iamconnor4/surge/internal/domain"
)

const getVenueById = `-- name: GetVenueById :one
SELECT id, name, created_at, updated_at
FROM venues WHERE id = $1
`

func (q *Queries) GetVenueById(ctx context.Context, id domain.VenueID) (Venue, error) {
	row := q.db.QueryRow(ctx, getVenueById, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
