// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venue_seats.sql

package db

import (
	"context"
	"time"

	"github.com/iamconnor4/surge/internal/domain"
)

type CreateVenueSeatsParams struct {
	ID             domain.VenueSeatID
	VenueSectionID domain.VenueSectionID
	RowLabel       string
	SeatLabel      string
	CreatedAt      time.Time
}

const getVenueSeatById = `-- name: GetVenueSeatById :one
SELECT id, venue_section_id, row_label, seat_label, created_at, updated_at
FROM venue_seats WHERE id = $1
`

func (q *Queries) GetVenueSeatById(ctx context.Context, id domain.VenueSeatID) (VenueSeat, error) {
	row := q.db.QueryRow(ctx, getVenueSeatById, id)
	var i VenueSeat
	err := row.Scan(
		&i.ID,
		&i.VenueSectionID,
		&i.RowLabel,
		&i.SeatLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
