// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venue_sections.sql

package db

import (
	"context"
	"time"

	"github.com/iamconnor4/surge/internal/domain"
)

const createVenueSection = `-- name: CreateVenueSection :exec
INSERT INTO venue_sections (
    id,
    venue_id,
    name,
    created_at
)
VALUES ($1, $2, $3, $4)
`

type CreateVenueSectionParams struct {
	ID        domain.VenueSectionID
	VenueID   domain.VenueID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateVenueSection(ctx context.Context, arg CreateVenueSectionParams) error {
	_, err := q.db.Exec(ctx, createVenueSection,
		arg.ID,
		arg.VenueID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const getVenueSectionById = `-- name: GetVenueSectionById :one
SELECT id, venue_id, name, created_at, updated_at
FROM venue_sections WHERE id = $1
`

func (q *Queries) GetVenueSectionById(ctx context.Context, id domain.VenueSectionID) (VenueSection, error) {
	row := q.db.QueryRow(ctx, getVenueSectionById, id)
	var i VenueSection
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
